name: Rootly Incident Action
description: Create an incident using the Rootly REST API.
author: PandasWhoCode

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: sunrise
  color: 'blue'

# Define your inputs here.
inputs:
  api_key:
    description: The API token to use for authentication with Rootly.
    required: true
  title:
    description: The title of the incident.
    required: true
    default: 'My Incident Title'
  kind:
    description:
      The kind of incident to create. One of 'test', 'test_sub', 'example',
      'example_sub', 'normal', 'normal_sub', 'backfilled', 'scheduled'.
    required: false
    default: 'normal'
  parent_incident_id:
    description: The ID of the parent incident, if any.
    required: false
  duplicate_inicident_id:
    description: The ID of the incident to mark as duplicate, if any.
    required: false
  create_public_incident:
    description: Set to true to create a public incident.
    required: false
    default: 'false'
  summary:
    description: The summary of the incident.
    required: false
  user_email:
    description: The email of the user to attach to the incident.
  severity:
    description: The severity of the incident.
    required: true
  alert_ids:
    description: Comma-separated list of alert IDs to link to the incident.
    required: false
  environments:
    description:
      The comma-separated names of the environments to create the incident for.
    required: false
  incident_types:
    description:
      The comma-separated names of the incident types to create the incident
      for.
    required: false
  services:
    description:
      The comma-separated names of the services to create the incident for.
    required: false
  functionalities:
    description:
      The comma-separated names of the functionalities to create the incident
      for.
    required: false
  teams:
    description:
      The comma-separated names of the teams to create the incident for.
    required: false
  causes:
    description:
      The comma-separated names of the causes to create the incident for.
    required: false
  labels:
    description:
      A comma-separated list of key:value pairs to create the alert for.
    required: false
  slack_channel_name:
    description: The name of the Slack channel to post updates to.
    required: false
  slack_channel_id:
    description: The ID of the Slack channel to post updates to.
    required: false
  slack_channel_url:
    description: The URL of the Slack channel to post updates to.
    required: false
  google_drive_parent_id:
    description: The Google Drive parent ID to create the incident document in.
    required: false
  google_drive_url:
    description: The URL of the Google Drive document for the incident.
    required: false
  notify_emails:
    description:
      Comma-separated list of email addresses to notify about the incident.
    required: false

# Define your outputs here.
outputs:
  incident-id:
    description: The ID of the created incident for API usage.

runs:
  using: node24
  main: dist/index.js
